/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nikola_malencic_chatapplication_JNIClass */

#ifndef _Included_nikola_malencic_chatapplication_JNIClass
#define _Included_nikola_malencic_chatapplication_JNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nikola_malencic_chatapplication_JNIClass
 * Method:    encryptDecrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nikola_malencic_chatapplication_JNIClass_encryptDecrypt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
